import {
  SiHtml5,
  SiCss3,
  SiBootstrap,
  SiTailwindcss,
  SiJavascript,
  SiTypescript,
  SiVuedotjs,
  SiReact,
  SiVite,
  SiAstro,
  SiShadcnui,
  SiAuth0,
  SiReactquery,
  SiReacttable,
  SiReacthookform,
  SiReactrouter,
  SiAxios,
  SiZod,
  SiFramer,
  SiRedux,
  SiPrisma,
  SiNextdotjs,
  SiNodedotjs,
  SiExpress,
  SiNestjs,
  SiGo,
  SiPhp,
  SiLaravel,
  SiKotlin,
  SiJetpackcompose,
  SiPostgresql,
  SiMysql,
  SiMongodb,
  SiFirebase,
  SiSupabase,
  SiJest,
  SiDocker,
  SiProbot,
  SiNpm,
  SiYarn,
  SiBun,
  SiGithub,
  SiVercel,
  SiPython,
  SiArduino,
  SiEspressif,
  SiRaspberrypi,
  SiPlatformio,
  SiCplusplus,
  SiMqtt,
  SiUnity,
  SiGodotengine,
  SiUnrealengine,
  SiThreedotjs,
  SiBlender,
} from "react-icons/si";

export const icons = {
  HTML: SiHtml5,
  CSS: SiCss3,
  Bootstrap: SiBootstrap,
  TailwindCSS: SiTailwindcss,
  JavaScript: SiJavascript,
  TypeScript: SiTypescript,
  "Vue.js": SiVuedotjs,
  "React.js": SiReact,
  Vite: SiVite,
  "Astro.js": SiAstro,
  "Shadcn UI": SiShadcnui,
  "NextAuth.js": SiAuth0,
  TanStack: SiReactquery,
  "React Table": SiReacttable,
  "React Hook Form": SiReacthookform,
  "React Router": SiReactrouter,
  Axios: SiAxios,
  Zod: SiZod,
  "Framer Motion": SiFramer,
  Redux: SiRedux,
  Prisma: SiPrisma,
  "Next.js": SiNextdotjs,
  "Node.js": SiNodedotjs,
  "Express.js": SiExpress,
  "Nest.js": SiNestjs,
  Go: SiGo,
  PHP: SiPhp,
  Laravel: SiLaravel,
  Kotlin: SiKotlin,
  "Jetpack Compose": SiJetpackcompose,
  PostgreSql: SiPostgresql,
  MySql: SiMysql,
  MongoDb: SiMongodb,
  Firebase: SiFirebase,
  Supabase: SiSupabase,
  Jest: SiJest,
  Docker: SiDocker,
  AI: SiProbot,
  Npm: SiNpm,
  Yarn: SiYarn,
  bun: SiBun,
  Github: SiGithub,
  Vercel: SiVercel,
  Python: SiPython,
  Arduino: SiArduino,
  ESP32: SiEspressif,
  "Raspberry Pi": SiRaspberrypi,
  PlatformIO: SiPlatformio,
  "C++": SiCplusplus,
  MQTT: SiMqtt,
  Unity: SiUnity,
  Godot: SiGodotengine,
  "Unreal Engine": SiUnrealengine,
  "Three.js": SiThreedotjs,
  Blender: SiBlender,
};
