-- ============================================================
-- Supabase Schema for Portfolio Projects & Automation
-- Run this in Supabase Dashboard -> SQL Editor -> New Query -> Run
-- ============================================================

-- 1. Create table public.projects
CREATE TABLE IF NOT EXISTS public.projects (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  slug TEXT UNIQUE NOT NULL,
  description TEXT,
  image TEXT,
  link_demo TEXT,
  link_github TEXT,
  stacks TEXT[] DEFAULT '{}',
  content TEXT,
  is_show BOOLEAN DEFAULT TRUE,
  is_featured BOOLEAN DEFAULT FALSE,
  category TEXT CHECK (category IN ('iot', 'game', 'web', 'web-frontend', 'web-backend', 'web-fullstack')) DEFAULT 'web',
  auto_generated BOOLEAN DEFAULT FALSE,
  source_repo TEXT,
  last_synced_at TIMESTAMPTZ DEFAULT NOW(),
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Indexes for fast query and sorting
CREATE INDEX IF NOT EXISTS idx_projects_slug ON public.projects(slug);
CREATE INDEX IF NOT EXISTS idx_projects_category ON public.projects(category);
CREATE INDEX IF NOT EXISTS idx_projects_is_show ON public.projects(is_show);

-- 3. Row Level Security (RLS)
ALTER TABLE public.projects ENABLE ROW LEVEL SECURITY;

-- Allow public read access to shown projects
DROP POLICY IF EXISTS "public read shown projects" ON public.projects;
CREATE POLICY "public read shown projects"
  ON public.projects FOR SELECT
  USING (is_show = true);

-- Service role bypasses RLS automatically for insert / update / delete

-- 4. Storage Bucket for project images (Optional/Recommended)
INSERT INTO storage.buckets (id, name, public)
VALUES ('projects', 'projects', true)
ON CONFLICT (id) DO NOTHING;

-- Policy to allow public read of project images
CREATE POLICY "Public read project images"
  ON storage.objects FOR SELECT
  USING (bucket_id = 'projects');

-- Policy to allow service role to manage storage objects
DROP POLICY IF EXISTS "Service role manage images" ON storage.objects;
CREATE POLICY "Service role manage images"
  ON storage.objects FOR ALL
  USING (auth.role() = 'service_role');

-- 5. Audit logs table for security tracking
CREATE TABLE IF NOT EXISTS public.audit_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  action TEXT NOT NULL,
  slug TEXT,
  actor TEXT,
  metadata JSONB,
  created_at TIMESTAMPTZ DEFAULT NOW()
);
ALTER TABLE public.audit_logs ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Service role manage audit logs"
  ON public.audit_logs FOR ALL
  USING (auth.role() = 'service_role');
  